export const characterOrder = [
    { rank: 1, name: "Abyss Titan", image: "AbyssTitan.jpeg" },
    { rank: 2, name: "Electro Dragon", image: "ElectroDragon.jpeg" },
    { rank: 3, name: "Colossus Titan", image: "ColossusTitan.jpeg" },
    { rank: 4, name: "Void Dragon", image: "VoidDragon.jpeg" },
    { rank: 5, name: "War Titan", image: "WarTitan.jpeg" },
    { rank: 6, name: "Inferno Dragon", image: "InfernoDragon.jpeg" },
    { rank: 7, name: "Celestial Beast", image: "CelestialBeast.jpeg" },
    { rank: 8, name: "Storm Dragon", image: "StormDragon.jpeg" },
    { rank: 9, name: "P.E.K.K.A", image: "PEKKA.jpeg" },
    { rank: 10, name: "Crystal Dragon", image: "CrystalDragon.jpeg" },
    { rank: 11, name: "Bone Titan", image: "BoneTitan.jpeg" },
    { rank: 12, name: "Ice Dragon", image: "IceDragon.jpeg" },
    { rank: 13, name: "Darkwood Treant", image: "DarkwoodTreant.jpeg" },
    { rank: 14, name: "Magma Golem", image: "MagmaGolem.jpeg" },
    { rank: 15, name: "Thunder Elemental", image: "ThunderElemental.jpeg" },
    { rank: 16, name: "Void Serpent", image: "VoidSerpent.jpeg" },
    { rank: 17, name: "Obsidian Golem", image: "ObsidianGolem.jpeg" },
    { rank: 18, name: "Infernal Hound", image: "InfernalHound.jpeg" },
    { rank: 19, name: "Crystal Elemental", image: "CrystalElemental.jpeg" },
    { rank: 20, name: "Lava Serpent", image: "LavaSerpent.jpeg" },
    { rank: 21, name: "Frost Beast", image: "FrostBeast.jpeg" },
    { rank: 22, name: "Ancient Stone Golem", image: "AncientStoneGolem.jpeg" },
    { rank: 23, name: "Arcane Elemental", image: "ArcaneElemental.jpeg" },
    { rank: 24, name: "Thunder Beast", image: "ThunderBeast.jpeg" },
    { rank: 25, name: "Frost Serpent", image: "FrostSerpent.jpeg" },
    { rank: 26, name: "Crystal Golem", image: "CrystalGolem.jpeg" },
    { rank: 27, name: "Shadow Beast", image: "ShadowBeast.jpeg" },
    { rank: 28, name: "Ice Golem", image: "IceGolem.jpeg" },
    { rank: 29, name: "Venom Beast", image: "VenomBeast.jpeg" },
    { rank: 30, name: "Magma Elemental", image: "MagmaElemental.jpeg" },
    { rank: 31, name: "Thunder Serpent", image: "ThunderSerpent.jpeg" },
    { rank: 32, name: "Ice Hound", image: "IceHound.jpeg" },
    { rank: 33, name: "Frost Elemental", image: "FrostElemental.jpeg" },
    { rank: 34, name: "Storm Hound", image: "StormHound.jpeg" },
    { rank: 35, name: "Void Wraith", image: "VoidWraith.jpeg" },
    { rank: 36, name: "Frost Wraith", image: "FrostWraith.jpeg" },
    { rank: 37, name: "Phantom Wraith", image: "PhantomWraith.jpeg" },
    { rank: 38, name: "Skull Brute", image: "SkullBrute.jpeg" },
    { rank: 39, name: "Golem", image: "Golem.jpeg" },
    { rank: 40, name: "Dragon", image: "Dragon.jpeg" }
];